"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MyERC721__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MyERC721__factory_1 = require("./MyERC721__factory");
Object.defineProperty(exports, "MyERC721__factory", { enumerable: true, get: function () { return MyERC721__factory_1.MyERC721__factory; } });
