"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MyERC1155__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MyERC1155__factory_1 = require("./MyERC1155__factory");
Object.defineProperty(exports, "MyERC1155__factory", { enumerable: true, get: function () { return MyERC1155__factory_1.MyERC1155__factory; } });
