"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Messenger__factory = exports.Book__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Book__factory_1 = require("./Book__factory");
Object.defineProperty(exports, "Book__factory", { enumerable: true, get: function () { return Book__factory_1.Book__factory; } });
var Messenger__factory_1 = require("./Messenger__factory");
Object.defineProperty(exports, "Messenger__factory", { enumerable: true, get: function () { return Messenger__factory_1.Messenger__factory; } });
